"""Shared data models for the Izumi analysis pipeline.

These models flow through all layers: analyzer → llm → sbom → gui.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .classifier import Classification


@dataclass
class FunctionSummary:
    """A C/C++ function together with its local-LLM-generated summary."""

    function_name: str
    file_path: Path
    start_line: int
    end_line: int
    body: str

    summary: str = ""
    """Natural-language summary generated by the local LLM."""

    approved: bool = False
    """True when the user has approved this summary for external-LLM submission."""


@dataclass
class Component:
    """An OSS component identified in the source tree.

    A component maps to one or more source files that logically belong
    together (e.g. all files under ``third_party/zlib/``).
    """

    name: str
    """Human-readable component name (e.g. 'zlib', 'openssl')."""

    directory: Path
    """Root directory of this component."""

    files: list[Path] = field(default_factory=list)
    classification: Classification = Classification.UNKNOWN
    classification_reason: str = ""

    license_expression: Optional[str] = None
    """SPDX license expression (e.g. 'MIT', 'Apache-2.0 OR MIT')."""

    copyright_texts: list[str] = field(default_factory=list)
    version: Optional[str] = None

    # ── LLM phase ─────────────────────────────────────────────────────────
    function_summaries: list[FunctionSummary] = field(default_factory=list)
    """Summaries of UNKNOWN functions, generated by the local LLM."""

    oss_hint: Optional[str] = None
    """Free-text hint from the external LLM ('possibly similar to zlib crc32()')."""

    # ── User judgement ────────────────────────────────────────────────────
    user_comment: Optional[str] = None
    user_confirmed: bool = False
    """True when the user has reviewed and accepted this component entry."""
